title: "Gwen Maudet"
description: "Research Associate in Mathematical Optimization, Machine Learning & IoT"
baseurl: ""
url: "https://gwenmaudet.github.io"
theme: minima
author: Gwen Maudet
email: gwen.maudet@laposte.net

markdown: kramdown

minima:
  skin: classic