title: "Gwen Maudet"
description: "Postdoctoral researcher"
baseurl: ""
url: "https://gwenmaudet.github.io"
theme: minima
author: Gwen Maudet
email: gwen.maudet@uni.lu

markdown: kramdown

# Explicitly set navigation order for the main pages
header_pages:
  - research.md
  - teaching.md
  - other.md

minima:
  skin: classic
