title: "Gwen Maudet"
description: "Postdoctoral Researcher | University of Luxembourg"
baseurl: ""
url: "https://gwenmaudet.github.io"
theme: minima
author: Gwen Maudet
email: gwen.maudet@imt-atlantique.fr

markdown: kramdown

minima:
  skin: classic