title: "Gwen Maudet"
description: "Post doctoral reasearcher"
baseurl: ""
url: "https://gwenmaudet.github.io"
theme: minima
author: Gwen Maudet
email: gwen.maudet@uni.lu

markdown: kramdown

minima:
  skin: classic