title: "Gwen Maudet"
description: "Postdoctoral researcher specializing in machine learning and mixed integer linear programming."
baseurl: ""
url: "https://gwenmaudet.github.io"
theme: minima
author: Gwen Maudet
email: gwen.maudet@uni.lu

markdown: kramdown

plugins:
  - jekyll-sitemap
minima:
  skin: classic
